const expect = require('chai').expect;
const nock = require('nock');
const getUserFollowers = require('../index').getUserFollowers;

describe('GET GitHub Followers', () => {
  const followersResponse = [
    {
      login: "alexandrepalagem",
      id: 5439929,
      avatar_url: "https://avatars.githubusercontent.com/u/5439929?v=3",
      gravatar_id: "",
      url: "https://api.github.com/users/alexandrepalagem",
      html_url: "https://github.com/alexandrepalagem",
      followers_url: "https://api.github.com/users/alexandrepalagem/followers",
      following_url: "https://api.github.com/users/alexandrepalagem/following{/other_user}",
      gists_url: "https://api.github.com/users/alexandrepalagem/gists{/gist_id}",
      starred_url: "https://api.github.com/users/alexandrepalagem/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/alexandrepalagem/subscriptions",
      organizations_url: "https://api.github.com/users/alexandrepalagem/orgs",
      repos_url: "https://api.github.com/users/alexandrepalagem/repos",
      events_url: "https://api.github.com/users/alexandrepalagem/events{/privacy}",
      received_events_url: "https://api.github.com/users/alexandrepalagem/received_events",
      type: "User",
      site_admin: false
    },
    {
      login: "angusshire",
      id: 5877145,
      avatar_url: "https://avatars.githubusercontent.com/u/5877145?v=3",
      gravatar_id: "",
      url: "https://api.github.com/users/angusshire",
      html_url: "https://github.com/angusshire",
      followers_url: "https://api.github.com/users/angusshire/followers",
      following_url: "https://api.github.com/users/angusshire/following{/other_user}",
      gists_url: "https://api.github.com/users/angusshire/gists{/gist_id}",
      starred_url: "https://api.github.com/users/angusshire/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/angusshire/subscriptions",
      organizations_url: "https://api.github.com/users/angusshire/orgs",
      repos_url: "https://api.github.com/users/angusshire/repos",
      events_url: "https://api.github.com/users/angusshire/events{/privacy}",
      received_events_url: "https://api.github.com/users/angusshire/received_events",
      type: "User",
      site_admin: false
    },
    {
      login: "willmenn",
      id: 7951799,
      avatar_url: "https://avatars.githubusercontent.com/u/7951799?v=3",
      gravatar_id: "",
      url: "https://api.github.com/users/willmenn",
      html_url: "https://github.com/willmenn",
      followers_url: "https://api.github.com/users/willmenn/followers",
      following_url: "https://api.github.com/users/willmenn/following{/other_user}",
      gists_url: "https://api.github.com/users/willmenn/gists{/gist_id}",
      starred_url: "https://api.github.com/users/willmenn/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/willmenn/subscriptions",
      organizations_url: "https://api.github.com/users/willmenn/orgs",
      repos_url: "https://api.github.com/users/willmenn/repos",
      events_url: "https://api.github.com/users/willmenn/events{/privacy}",
      received_events_url: "https://api.github.com/users/willmenn/received_events",
      type: "User",
      site_admin: false
    },
    {
      login: "jeffhsta",
      id: 4042266,
      avatar_url: "https://avatars.githubusercontent.com/u/4042266?v=3",
      gravatar_id: "",
      url: "https://api.github.com/users/jeffhsta",
      html_url: "https://github.com/jeffhsta",
      followers_url: "https://api.github.com/users/jeffhsta/followers",
      following_url: "https://api.github.com/users/jeffhsta/following{/other_user}",
      gists_url: "https://api.github.com/users/jeffhsta/gists{/gist_id}",
      starred_url: "https://api.github.com/users/jeffhsta/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/jeffhsta/subscriptions",
      organizations_url: "https://api.github.com/users/jeffhsta/orgs",
      repos_url: "https://api.github.com/users/jeffhsta/repos",
      events_url: "https://api.github.com/users/jeffhsta/events{/privacy}",
      received_events_url: "https://api.github.com/users/jeffhsta/received_events",
      type: "User",
      site_admin: false
    },
    {
      login: "thaishamilton",
      id: 4603029,
      avatar_url: "https://avatars.githubusercontent.com/u/4603029?v=3",
      gravatar_id: "",
      url: "https://api.github.com/users/thaishamilton",
      html_url: "https://github.com/thaishamilton",
      followers_url: "https://api.github.com/users/thaishamilton/followers",
      following_url: "https://api.github.com/users/thaishamilton/following{/other_user}",
      gists_url: "https://api.github.com/users/thaishamilton/gists{/gist_id}",
      starred_url: "https://api.github.com/users/thaishamilton/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/thaishamilton/subscriptions",
      organizations_url: "https://api.github.com/users/thaishamilton/orgs",
      repos_url: "https://api.github.com/users/thaishamilton/repos",
      events_url: "https://api.github.com/users/thaishamilton/events{/privacy}",
      received_events_url: "https://api.github.com/users/thaishamilton/received_events",
      type: "User",
      site_admin: false
    },
    {
      login: "marcoblos",
      id: 8642935,
      avatar_url: "https://avatars.githubusercontent.com/u/8642935?v=3",
      gravatar_id: "",
      url: "https://api.github.com/users/marcoblos",
      html_url: "https://github.com/marcoblos",
      followers_url: "https://api.github.com/users/marcoblos/followers",
      following_url: "https://api.github.com/users/marcoblos/following{/other_user}",
      gists_url: "https://api.github.com/users/marcoblos/gists{/gist_id}",
      starred_url: "https://api.github.com/users/marcoblos/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/marcoblos/subscriptions",
      organizations_url: "https://api.github.com/users/marcoblos/orgs",
      repos_url: "https://api.github.com/users/marcoblos/repos",
      events_url: "https://api.github.com/users/marcoblos/events{/privacy}",
      received_events_url: "https://api.github.com/users/marcoblos/received_events",
      type: "User",
      site_admin: false
    },
    {
      login: "iagodahlem",
      id: 11875867,
      avatar_url: "https://avatars.githubusercontent.com/u/11875867?v=3",
      gravatar_id: "",
      url: "https://api.github.com/users/iagodahlem",
      html_url: "https://github.com/iagodahlem",
      followers_url: "https://api.github.com/users/iagodahlem/followers",
      following_url: "https://api.github.com/users/iagodahlem/following{/other_user}",
      gists_url: "https://api.github.com/users/iagodahlem/gists{/gist_id}",
      starred_url: "https://api.github.com/users/iagodahlem/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/iagodahlem/subscriptions",
      organizations_url: "https://api.github.com/users/iagodahlem/orgs",
      repos_url: "https://api.github.com/users/iagodahlem/repos",
      events_url: "https://api.github.com/users/iagodahlem/events{/privacy}",
      received_events_url: "https://api.github.com/users/iagodahlem/received_events",
      type: "User",
      site_admin: false
    },
    {
      login: "waldemarnt",
      id: 5835706,
      avatar_url: "https://avatars.githubusercontent.com/u/5835706?v=3",
      gravatar_id: "",
      url: "https://api.github.com/users/waldemarnt",
      html_url: "https://github.com/waldemarnt",
      followers_url: "https://api.github.com/users/waldemarnt/followers",
      following_url: "https://api.github.com/users/waldemarnt/following{/other_user}",
      gists_url: "https://api.github.com/users/waldemarnt/gists{/gist_id}",
      starred_url: "https://api.github.com/users/waldemarnt/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/waldemarnt/subscriptions",
      organizations_url: "https://api.github.com/users/waldemarnt/orgs",
      repos_url: "https://api.github.com/users/waldemarnt/repos",
      events_url: "https://api.github.com/users/waldemarnt/events{/privacy}",
      received_events_url: "https://api.github.com/users/waldemarnt/received_events",
      type: "User",
      site_admin: false
    },
    {
      login: "marlonbernardes",
      id: 2975955,
      avatar_url: "https://avatars.githubusercontent.com/u/2975955?v=3",
      gravatar_id: "",
      url: "https://api.github.com/users/marlonbernardes",
      html_url: "https://github.com/marlonbernardes",
      followers_url: "https://api.github.com/users/marlonbernardes/followers",
      following_url: "https://api.github.com/users/marlonbernardes/following{/other_user}",
      gists_url: "https://api.github.com/users/marlonbernardes/gists{/gist_id}",
      starred_url: "https://api.github.com/users/marlonbernardes/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/marlonbernardes/subscriptions",
      organizations_url: "https://api.github.com/users/marlonbernardes/orgs",
      repos_url: "https://api.github.com/users/marlonbernardes/repos",
      events_url: "https://api.github.com/users/marlonbernardes/events{/privacy}",
      received_events_url: "https://api.github.com/users/marlonbernardes/received_events",
      type: "User",
      site_admin: false
    },
    {
      login: "roberto",
      id: 4188,
      avatar_url: "https://avatars.githubusercontent.com/u/4188?v=3",
      gravatar_id: "",
      url: "https://api.github.com/users/roberto",
      html_url: "https://github.com/roberto",
      followers_url: "https://api.github.com/users/roberto/followers",
      following_url: "https://api.github.com/users/roberto/following{/other_user}",
      gists_url: "https://api.github.com/users/roberto/gists{/gist_id}",
      starred_url: "https://api.github.com/users/roberto/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/roberto/subscriptions",
      organizations_url: "https://api.github.com/users/roberto/orgs",
      repos_url: "https://api.github.com/users/roberto/repos",
      events_url: "https://api.github.com/users/roberto/events{/privacy}",
      received_events_url: "https://api.github.com/users/roberto/received_events",
      type: "User",
      site_admin: false
    },
    {
      login: "sarahcaixeta",
      id: 3097875,
      avatar_url: "https://avatars.githubusercontent.com/u/3097875?v=3",
      gravatar_id: "",
      url: "https://api.github.com/users/sarahcaixeta",
      html_url: "https://github.com/sarahcaixeta",
      followers_url: "https://api.github.com/users/sarahcaixeta/followers",
      following_url: "https://api.github.com/users/sarahcaixeta/following{/other_user}",
      gists_url: "https://api.github.com/users/sarahcaixeta/gists{/gist_id}",
      starred_url: "https://api.github.com/users/sarahcaixeta/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/sarahcaixeta/subscriptions",
      organizations_url: "https://api.github.com/users/sarahcaixeta/orgs",
      repos_url: "https://api.github.com/users/sarahcaixeta/repos",
      events_url: "https://api.github.com/users/sarahcaixeta/events{/privacy}",
      received_events_url: "https://api.github.com/users/sarahcaixeta/received_events",
      type: "User",
      site_admin: false
    },
    {
      login: "daniellucasss",
      id: 13783376,
      avatar_url: "https://avatars.githubusercontent.com/u/13783376?v=3",
      gravatar_id: "",
      url: "https://api.github.com/users/daniellucasss",
      html_url: "https://github.com/daniellucasss",
      followers_url: "https://api.github.com/users/daniellucasss/followers",
      following_url: "https://api.github.com/users/daniellucasss/following{/other_user}",
      gists_url: "https://api.github.com/users/daniellucasss/gists{/gist_id}",
      starred_url: "https://api.github.com/users/daniellucasss/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/daniellucasss/subscriptions",
      organizations_url: "https://api.github.com/users/daniellucasss/orgs",
      repos_url: "https://api.github.com/users/daniellucasss/repos",
      events_url: "https://api.github.com/users/daniellucasss/events{/privacy}",
      received_events_url: "https://api.github.com/users/daniellucasss/received_events",
      type: "User",
      site_admin: false
    },
    {
      login: "leoalmig",
      id: 6754058,
      avatar_url: "https://avatars.githubusercontent.com/u/6754058?v=3",
      gravatar_id: "",
      url: "https://api.github.com/users/leoalmig",
      html_url: "https://github.com/leoalmig",
      followers_url: "https://api.github.com/users/leoalmig/followers",
      following_url: "https://api.github.com/users/leoalmig/following{/other_user}",
      gists_url: "https://api.github.com/users/leoalmig/gists{/gist_id}",
      starred_url: "https://api.github.com/users/leoalmig/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/leoalmig/subscriptions",
      organizations_url: "https://api.github.com/users/leoalmig/orgs",
      repos_url: "https://api.github.com/users/leoalmig/repos",
      events_url: "https://api.github.com/users/leoalmig/events{/privacy}",
      received_events_url: "https://api.github.com/users/leoalmig/received_events",
      type: "User",
      site_admin: false
    },
    {
      login: "OtavioRMachado",
      id: 4467006,
      avatar_url: "https://avatars.githubusercontent.com/u/4467006?v=3",
      gravatar_id: "",
      url: "https://api.github.com/users/OtavioRMachado",
      html_url: "https://github.com/OtavioRMachado",
      followers_url: "https://api.github.com/users/OtavioRMachado/followers",
      following_url: "https://api.github.com/users/OtavioRMachado/following{/other_user}",
      gists_url: "https://api.github.com/users/OtavioRMachado/gists{/gist_id}",
      starred_url: "https://api.github.com/users/OtavioRMachado/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/OtavioRMachado/subscriptions",
      organizations_url: "https://api.github.com/users/OtavioRMachado/orgs",
      repos_url: "https://api.github.com/users/OtavioRMachado/repos",
      events_url: "https://api.github.com/users/OtavioRMachado/events{/privacy}",
      received_events_url: "https://api.github.com/users/OtavioRMachado/received_events",
      type: "User",
      site_admin: false
    },
    {
      login: "pedrro",
      id: 4137355,
      avatar_url: "https://avatars.githubusercontent.com/u/4137355?v=3",
      gravatar_id: "",
      url: "https://api.github.com/users/pedrro",
      html_url: "https://github.com/pedrro",
      followers_url: "https://api.github.com/users/pedrro/followers",
      following_url: "https://api.github.com/users/pedrro/following{/other_user}",
      gists_url: "https://api.github.com/users/pedrro/gists{/gist_id}",
      starred_url: "https://api.github.com/users/pedrro/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/pedrro/subscriptions",
      organizations_url: "https://api.github.com/users/pedrro/orgs",
      repos_url: "https://api.github.com/users/pedrro/repos",
      events_url: "https://api.github.com/users/pedrro/events{/privacy}",
      received_events_url: "https://api.github.com/users/pedrro/received_events",
      type: "User",
      site_admin: false
    },
    {
      login: "vtrbtf",
      id: 860053,
      avatar_url: "https://avatars.githubusercontent.com/u/860053?v=3",
      gravatar_id: "",
      url: "https://api.github.com/users/vtrbtf",
      html_url: "https://github.com/vtrbtf",
      followers_url: "https://api.github.com/users/vtrbtf/followers",
      following_url: "https://api.github.com/users/vtrbtf/following{/other_user}",
      gists_url: "https://api.github.com/users/vtrbtf/gists{/gist_id}",
      starred_url: "https://api.github.com/users/vtrbtf/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/vtrbtf/subscriptions",
      organizations_url: "https://api.github.com/users/vtrbtf/orgs",
      repos_url: "https://api.github.com/users/vtrbtf/repos",
      events_url: "https://api.github.com/users/vtrbtf/events{/privacy}",
      received_events_url: "https://api.github.com/users/vtrbtf/received_events",
      type: "User",
      site_admin: false
    },
    {
      login: "Mrzeron",
      id: 17607933,
      avatar_url: "https://avatars.githubusercontent.com/u/17607933?v=3",
      gravatar_id: "",
      url: "https://api.github.com/users/Mrzeron",
      html_url: "https://github.com/Mrzeron",
      followers_url: "https://api.github.com/users/Mrzeron/followers",
      following_url: "https://api.github.com/users/Mrzeron/following{/other_user}",
      gists_url: "https://api.github.com/users/Mrzeron/gists{/gist_id}",
      starred_url: "https://api.github.com/users/Mrzeron/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/Mrzeron/subscriptions",
      organizations_url: "https://api.github.com/users/Mrzeron/orgs",
      repos_url: "https://api.github.com/users/Mrzeron/repos",
      events_url: "https://api.github.com/users/Mrzeron/events{/privacy}",
      received_events_url: "https://api.github.com/users/Mrzeron/received_events",
      type: "User",
      site_admin: false
    },
    {
      login: "othman853",
      id: 4705127,
      avatar_url: "https://avatars.githubusercontent.com/u/4705127?v=3",
      gravatar_id: "",
      url: "https://api.github.com/users/othman853",
      html_url: "https://github.com/othman853",
      followers_url: "https://api.github.com/users/othman853/followers",
      following_url: "https://api.github.com/users/othman853/following{/other_user}",
      gists_url: "https://api.github.com/users/othman853/gists{/gist_id}",
      starred_url: "https://api.github.com/users/othman853/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/othman853/subscriptions",
      organizations_url: "https://api.github.com/users/othman853/orgs",
      repos_url: "https://api.github.com/users/othman853/repos",
      events_url: "https://api.github.com/users/othman853/events{/privacy}",
      received_events_url: "https://api.github.com/users/othman853/received_events",
      type: "User",
      site_admin: false
    }
  ];

  it('returns a user followers username only', function(done) {
    const username = 'lucaslago';

    nock('https://api.github.com')
      .get(`/users/${username}/followers`)
      .reply(200, followersResponse);

    getUserFollowers(username)
      .then(followers => {
        expect(followers).to.be.instanceof(Array);
        expect(followers).to.have.length.above(1);
        followers.forEach(f => expect(f).to.be.a('string'));
        done();
      })
      .catch(err => done(err));

  });
});
